/* eslint-disable */
// This file is auto-generated by @granite-js/react-native. DO NOT EDIT.
import { Route as _AboutRoute } from '../pages/about';
import { Route as _ExchangeRoute } from '../pages/exchange';
import { Route as _GalleryRoute } from '../pages/gallery';
import { Route as _IndexRoute } from '../pages/';

declare module '@granite-js/react-native' {
  interface RegisterScreenInput {
    '/about': (typeof _AboutRoute)['_inputType'];
    '/exchange': (typeof _ExchangeRoute)['_inputType'];
    '/gallery': (typeof _GalleryRoute)['_inputType'];
    '/': (typeof _IndexRoute)['_inputType'];
  }

  interface RegisterScreen {
    '/about': (typeof _AboutRoute)['_outputType'];
    '/exchange': (typeof _ExchangeRoute)['_outputType'];
    '/gallery': (typeof _GalleryRoute)['_outputType'];
    '/': (typeof _IndexRoute)['_outputType'];
  }
}
